language: julia
os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
- julia -e 'cd(Pkg.dir("Exercism")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
